# Generated by Django 6.0.7 on 2026-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('om', 'OM'), ('bod', 'BOD'), ('am', 'AM'), ('kcs', 'KCS'), ('bql', 'BQL'), ('trainer', 'Trainer'), ('employee', 'Học viên')], default='trainer', max_length=20),
        ),
    ]
