# Generated by Django 6.0.7 on 2026-08-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('brand_hex', models.CharField(default='#1e6f5c', max_length=7)),
                ('brand_key', models.CharField(blank=True, max_length=50, null=True)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_settings', to='accounts.tenant')),
            ],
        ),
    ]
