# Generated by Django 6.0.7 on 2026-08-24 01:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_brandsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_display_name', models.CharField(blank=True, default='Phòng Đào tạo', max_length=255)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('weekly_enabled', models.BooleanField(default=False)),
                ('weekly_weekday', models.PositiveSmallIntegerField(default=0)),
                ('weekly_hour', models.PositiveSmallIntegerField(default=8)),
                ('monthly_enabled', models.BooleanField(default=False)),
                ('monthly_day', models.PositiveSmallIntegerField(default=1)),
                ('monthly_hour', models.PositiveSmallIntegerField(default=8)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_pass_percent', models.DecimalField(decimal_places=2, default=Decimal('80'), max_digits=5)),
                ('skill_pass_percent', models.DecimalField(decimal_places=2, default=Decimal('85'), max_digits=5)),
                ('weight_exam', models.DecimalField(decimal_places=2, default=Decimal('0.4'), max_digits=4)),
                ('weight_practice', models.DecimalField(decimal_places=2, default=Decimal('0.6'), max_digits=4)),
                ('weight_theory', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5)),
                ('weight_practical', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5)),
                ('days_staff', models.PositiveIntegerField(default=15)),
                ('days_supervisor_deputy', models.PositiveIntegerField(default=30)),
                ('days_manager_chef', models.PositiveIntegerField(default=60)),
                ('probation_pass_rule', models.TextField(blank=True, default='5 điều kiện hoa hồng trainer: hoàn thành LMS + thi đạt (exam_pass_percent) + checklist đào tạo 100% + đánh giá kỹ năng đạt (skill_pass_percent) + làm đủ 1 tháng.')),
                ('allowance_per_person', models.DecimalField(decimal_places=2, default=Decimal('300000'), max_digits=12)),
                ('allowance_exam_min', models.DecimalField(decimal_places=2, default=Decimal('80'), max_digits=5)),
                ('allowance_skill_min', models.DecimalField(decimal_places=2, default=Decimal('85'), max_digits=5)),
                ('allowance_scope', models.JSONField(blank=True, default=list)),
                ('cert_positions_required', models.PositiveIntegerField(default=3)),
                ('cert_program_rule', models.TextField(blank=True, default='Đủ số vị trí tối thiểu (cert_positions_required) đã hoàn thành để đạt điều kiện chương trình chứng chỉ theo vị trí.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_config', to='accounts.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradingConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=500)),
                ('new_value', models.CharField(blank=True, max_length=500)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_config_history', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
