# Generated by Django 6.0.7 on 2026-08-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailsettings_gradingconfig_gradingconfighistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
