# Generated by Django 6.0.7 on 2026-08-29 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=20)),
                ('old_keys', models.JSONField(blank=True, default=list)),
                ('new_keys', models.JSONField(blank=True, default=list)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_config_history', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('om', 'OM'), ('bod', 'BOD'), ('am', 'AM'), ('kcs', 'KCS'), ('bql', 'BQL'), ('trainer', 'Trainer'), ('employee', 'Học viên')], max_length=20)),
                ('menu_keys', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_configs', to='accounts.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'role')},
            },
        ),
    ]
