# Generated by Django 6.0.7 on 2026-08-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rolemenuconfighistory_rolemenuconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingconfig',
            name='kpi_mode',
            field=models.CharField(choices=[('sessions', 'Đếm số buổi'), ('hours', 'Đếm giờ đào tạo')], default='sessions', max_length=10),
        ),
    ]
