# Generated by Django 6.0.7 on 2026-09-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_gradingconfig_kpi_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingconfig',
            name='has_probation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='probation_window_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='roadmap_window_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='sequential_positions',
            field=models.BooleanField(default=True),
        ),
    ]
