"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-q6y-2y)#6+s*+fun$hl_h*3_*+k%m=ar%t^)p^i!*vi(k662i7',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'accounts',
    'restaurants',
    'employees',
    'checklist',
    'evaluation',
    'kpi',
    'cls_sync',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'accounts.pagination.DefaultPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS — frontend Vite dev server
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
    if o.strip()
]

# CLS (hệ thống LMS ngoài) — đồng bộ kết quả học/thi, xem cls_sync/management/commands/sync_cls.py
CLS_SECRET_KEY = os.environ.get('CLS_SECRET_KEY', '')
CLS_API_BASE = os.environ.get('CLS_API_BASE', 'https://eapiv4.cls.vn/api/HRM')
CLS_EXAM_START_DATE = os.environ.get('CLS_EXAM_START_DATE', '2024-01-01')
CLS_PROBATION_EXAM_TYPES = [
    t.strip().upper()
    for t in os.environ.get('CLS_PROBATION_EXAM_TYPES', 'NV,10N,15N,30N').split(',')
    if t.strip()
]
CLS_ONBOARDING_PASS_SCORE = float(os.environ.get('CLS_ONBOARDING_PASS_SCORE', '80'))

# Nguồn tuyển dụng (CSV export, vd Google Sheet Publish to web > CSV) cho sync_recruitment
RECRUITMENT_SOURCE_CSV_URL = os.environ.get('RECRUITMENT_SOURCE_CSV_URL', '')

# Supabase Storage — lưu ảnh minh chứng đào tạo + biên bản PDF (xem checklist/storage.py)
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_SERVICE_KEY = os.environ.get('SUPABASE_SERVICE_KEY', '')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'training-evidence')

# Phụ cấp/Hoa hồng trainer — port CommissionService.gs (giá trị mặc định của bản Apps Script cũ,
# đọc từ sheet Config trong bản gốc; ở đây cấu hình qua .env, có thể chỉnh khi cần)
COMMISSION_AMOUNT = float(os.environ.get('COMMISSION_AMOUNT', '300000'))
COMMISSION_SKILL_THRESHOLD = float(os.environ.get('COMMISSION_SKILL_THRESHOLD', '85'))
COMMISSION_EXAM_THRESHOLD = float(os.environ.get('COMMISSION_EXAM_THRESHOLD', '80'))
COMMISSION_WORKED_DAYS = int(os.environ.get('COMMISSION_WORKED_DAYS', '30'))
# Danh sách Restaurant.code được áp dụng hoa hồng; để trống = áp dụng tất cả nhà hàng
# (khác bản gốc: bản gốc mặc định giới hạn 4 nhà hàng pilot của công ty cũ, không phù hợp
# dữ liệu tenant mới nên mặc định ở đây là không giới hạn — xem trao đổi trong sprint KPI).
COMMISSION_RESTAURANT_ALLOWLIST = [
    c.strip() for c in os.environ.get('COMMISSION_RESTAURANT_ALLOWLIST', '').split(',') if c.strip()
]

# KPI đào tạo — số buổi/tháng mục tiêu cho mỗi nhà hàng (Config.kpiTarget() bản gốc, mặc định 3)
KPI_TARGET_PER_MONTH = int(os.environ.get('KPI_TARGET_PER_MONTH', '3'))

# Thời hạn thử việc mặc định (ngày) khi Employee.probation_days chưa được gán — port
# Config.gs PROBATION_S_DAYS/PROBATION_O_DAYS. S = nhân viên thường, O = quản lý/giám sát.
PROBATION_S_DAYS = int(os.environ.get('PROBATION_S_DAYS', '15'))
PROBATION_O_DAYS = int(os.environ.get('PROBATION_O_DAYS', '60'))
# Ngưỡng "sắp đến hạn thử việc" trên dashboard (days_left <= ngưỡng này, gồm cả quá hạn/âm)
PROBATION_DEADLINE_WARN_DAYS = int(os.environ.get('PROBATION_DEADLINE_WARN_DAYS', '10'))
