"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-q6y-2y)#6+s*+fun$hl_h*3_*+k%m=ar%t^)p^i!*vi(k662i7',
)

# SECURITY WARNING: don't run with debug turned on in production!
# So khop khong phan biet hoa/thuong ('true'/'True'/'TRUE'/'1'/...) - '== "True"' cu se am
# tham thanh False neu secret dat chu thuong, giong loi da gap voi EMAIL_USE_TLS ben duoi.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() in ('true', '1', 'yes', 'on')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Domain(s) tin cay de nhan POST/PUT/PATCH/DELETE qua CSRF check (vd Django admin) - can co
# scheme (https://...). Chi anh huong request dung session/cookie (admin site); API JWT
# (SessionAuthentication khong bat) khong bi anh huong.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'accounts',
    'restaurants',
    'employees',
    'checklist',
    'evaluation',
    'kpi',
    'cls_sync',
    'sourcing',
    'reports',
    'courses',
    'exams',
    'integration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'accounts.permissions.BodReadOnly',
        'accounts.permissions.EmployeeLearnerScope',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'accounts.pagination.DefaultPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS — frontend Vite dev server
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
    if o.strip()
]

# CLS (hệ thống LMS ngoài) — đồng bộ kết quả học/thi, xem cls_sync/management/commands/sync_cls.py
CLS_SECRET_KEY = os.environ.get('CLS_SECRET_KEY', '')
CLS_API_BASE = os.environ.get('CLS_API_BASE', 'https://eapiv4.cls.vn/api/HRM')
CLS_EXAM_START_DATE = os.environ.get('CLS_EXAM_START_DATE', '2024-01-01')
CLS_PROBATION_EXAM_TYPES = [
    t.strip().upper()
    for t in os.environ.get('CLS_PROBATION_EXAM_TYPES', 'NV,10N,15N,30N').split(',')
    if t.strip()
]
CLS_ONBOARDING_PASS_SCORE = float(os.environ.get('CLS_ONBOARDING_PASS_SCORE', '80'))

# Nguồn tuyển dụng (CSV export, vd Google Sheet Publish to web > CSV) cho sync_recruitment
RECRUITMENT_SOURCE_CSV_URL = os.environ.get('RECRUITMENT_SOURCE_CSV_URL', '')

# Nguồn dữ liệu source (CSV Publish to web) cho các lệnh import_* — di dữ liệu từ hệ cũ
RESTAURANTS_SOURCE_CSV_URL = os.environ.get('RESTAURANTS_SOURCE_CSV_URL', '')
CHECKLIST_SOURCE_CSV_URL = os.environ.get('CHECKLIST_SOURCE_CSV_URL', '')
DOCUMENTS_SOURCE_CSV_URL = os.environ.get('DOCUMENTS_SOURCE_CSV_URL', '')

# Google Drive/Sheets (service account) - dung cho import_july_data (ETL minh chung/danh gia/
# phieu ket qua tu Drive vao v2.1). JSON string nguyen van cua key file service account.
GOOGLE_SERVICE_ACCOUNT_JSON = os.environ.get('GOOGLE_SERVICE_ACCOUNT_JSON', '')
TRAINING_DRIVE_ROOT_FOLDER_ID = os.environ.get('TRAINING_DRIVE_ROOT_FOLDER_ID', '')
TRAINING_DB_SHEET_ID = os.environ.get('TRAINING_DB_SHEET_ID', '')
# Tab 'app_employees' (diem/ket qua) KHONG nam trong spreadsheet TRAINING_DB_SHEET_ID (Sheets
# API bao "Unable to parse range") - doc rieng qua link CSV "Publish to web" cong khai bang
# requests, giong cac lenh import_* khac (xem config/csv_source.py).
APP_EMPLOYEES_CSV_URL = os.environ.get(
    'APP_EMPLOYEES_CSV_URL',
    'https://docs.google.com/spreadsheets/d/e/2PACX-1vQH4c0XK5A17FAHSn1hEdWsuDvSUsxf9Ulp4yAf-90hAsvKfbdKh0_uDgwk1N3y0kTb8vlAXXd304qu/pub?gid=1267495868&single=true&output=csv',
)

# Kho lưu file minh chứng/PDF — chọn backend qua STORAGE_BACKEND: 'r2' (mặc định) | 'supabase'.
STORAGE_BACKEND = os.environ.get('STORAGE_BACKEND', 'r2')

# Cloudflare R2 (chuẩn S3) — mặc định. Xem checklist/storage.py.
R2_ACCOUNT_ID = os.environ.get('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET = os.environ.get('R2_BUCKET', '')
R2_PUBLIC_BASE_URL = os.environ.get('R2_PUBLIC_BASE_URL', '')  # vd https://pub-xxxx.r2.dev

# Supabase Storage — giữ để dự phòng/rollback (đặt STORAGE_BACKEND=supabase để dùng lại).
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_SERVICE_KEY = os.environ.get('SUPABASE_SERVICE_KEY', '')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'training-evidence')

# Phụ cấp/Hoa hồng trainer — port CommissionService.gs (giá trị mặc định của bản Apps Script cũ,
# đọc từ sheet Config trong bản gốc; ở đây cấu hình qua .env, có thể chỉnh khi cần)
COMMISSION_AMOUNT = float(os.environ.get('COMMISSION_AMOUNT', '300000'))
COMMISSION_SKILL_THRESHOLD = float(os.environ.get('COMMISSION_SKILL_THRESHOLD', '85'))
COMMISSION_EXAM_THRESHOLD = float(os.environ.get('COMMISSION_EXAM_THRESHOLD', '80'))
COMMISSION_WORKED_DAYS = int(os.environ.get('COMMISSION_WORKED_DAYS', '30'))
# Danh sách Restaurant.code được áp dụng hoa hồng; để trống = áp dụng tất cả nhà hàng
# (khác bản gốc: bản gốc mặc định giới hạn 4 nhà hàng pilot của công ty cũ, không phù hợp
# dữ liệu tenant mới nên mặc định ở đây là không giới hạn — xem trao đổi trong sprint KPI).
COMMISSION_RESTAURANT_ALLOWLIST = [
    c.strip() for c in os.environ.get('COMMISSION_RESTAURANT_ALLOWLIST', '').split(',') if c.strip()
]

# Nguoi ky "Xac nhan tu Phong Dao tao" o cuoi phieu ket qua thu viec (employees/pdf.py) - doi
# duoc qua .env ma khong can sua code khi doi nguoi ky.
RESULT_SIGNER_NAME = os.environ.get('RESULT_SIGNER_NAME', 'Nguyễn Văn Tam')
RESULT_SIGNER_TITLE = os.environ.get('RESULT_SIGNER_TITLE', 'Phó Phòng Đào tạo')

# KPI đào tạo — số buổi/tháng mục tiêu cho mỗi nhà hàng (Config.kpiTarget() bản gốc, mặc định 3)
KPI_TARGET_PER_MONTH = int(os.environ.get('KPI_TARGET_PER_MONTH', '3'))

# Thời hạn thử việc mặc định (ngày) khi Employee.probation_days chưa được gán — port
# Config.gs PROBATION_S_DAYS/PROBATION_O_DAYS. S = nhân viên thường, O = quản lý/giám sát.
PROBATION_S_DAYS = int(os.environ.get('PROBATION_S_DAYS', '15'))
PROBATION_O_DAYS = int(os.environ.get('PROBATION_O_DAYS', '60'))
# Ngưỡng "sắp đến hạn thử việc" trên dashboard (days_left <= ngưỡng này, gồm cả quá hạn/âm)
PROBATION_DEADLINE_WARN_DAYS = int(os.environ.get('PROBATION_DEADLINE_WARN_DAYS', '10'))

# ---- Email (M2.5) ----
# Đặt EMAIL_HOST/EMAIL_HOST_USER/EMAIL_HOST_PASSWORD (secret) để gửi mail thật (vd Gmail SMTP:
# host smtp.gmail.com, port 587, dùng App Password). Chưa đặt → in ra console, không gửi thật.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# So khop khong phan biet hoa/thuong - '== "True"' cu se am tham thanh False neu secret dat
# 'true'/'TRUE'/'1' (chu thuong), khien SMTP goi khong co STARTTLS -> loi "SMTP AUTH extension
# not supported by server" tu server yeu cau TLS.
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').strip().lower() in ('true', '1', 'yes', 'on')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@training.local'
)
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend'
)

# ---- Báo cáo đào tạo tuần/tháng (reports app) ----
REPORT_TO = [e.strip() for e in os.environ.get('REPORT_TO', '').split(',') if e.strip()]
REPORT_CC = [e.strip() for e in os.environ.get('REPORT_CC', '').split(',') if e.strip()]
# CSV "Tổ chức đào tạo" (Publish to web > CSV) - cột: Training_Date, Employee_ID, Employee_Name,
# Cousera_Code, Cousera_Name, Class_Code, Learner_Group, Assignment_Status, Participation_Status,
# Training_Month (mỗi dòng = 1 lượt gán/tham gia của 1 NV vào 1 lớp).
TRAINING_DATA_CSV_URL = os.environ.get('TRAINING_DATA_CSV_URL', '')
# CSV "Chấm dịch vụ nhà hàng" - cột theo vị trí (thư mục nguồn không có header chuẩn hoá tên):
# D=ngày chấm, F=tên nhà hàng, I=Score_Criteria, J=Criteria, N=Result_Score, O=Department_Name.
SERVICE_AUDIT_CSV_URL = os.environ.get('SERVICE_AUDIT_CSV_URL', '')
# Phân tích GPT (chỉ khối chấm dịch vụ) - để trống OPENAI_API_KEY = bỏ qua phần phân tích.
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o-mini')
