# Generated by Django 6.0.7 on 2026-07-13 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_restaurant'),
        ('checklist', '0003_trainingprogress_note_and_more'),
        ('employees', '0002_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cond_lms', models.BooleanField(default=False)),
                ('cond_exam', models.BooleanField(default=False)),
                ('cond_training', models.BooleanField(default=False)),
                ('cond_skill_eval', models.BooleanField(default=False)),
                ('cond_worked_1month', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Chờ'), ('eligible', 'Đủ điều kiện'), ('retrain', 'Đào tạo lại'), ('paid', 'Đã chi'), ('na', 'Không áp dụng')], default='waiting', max_length=10)),
                ('retrain_deadline', models.DateField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='accounts.tenant')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_earned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KpiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('img_tailieu', models.URLField(blank=True, max_length=500)),
                ('img_lythuyet', models.URLField(blank=True, max_length=500)),
                ('img_thuchanh', models.URLField(blank=True, max_length=500)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_sessions', to='checklist.document')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_sessions', to='restaurants.restaurant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_sessions', to='accounts.tenant')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_sessions_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KpiParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_url', models.URLField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_participations', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_participants', to='accounts.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kpi.kpisession')),
            ],
            options={
                'unique_together': {('session', 'employee')},
            },
        ),
    ]
