# Generated by Django 6.0.7 on 2026-08-07 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_url'),
        ('kpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kpi_bql', 'Báo cáo KPI BQL'), ('allowance', 'Phiếu phụ cấp trainer')], max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pdf_url', models.URLField(max_length=500)),
                ('exported_at', models.DateTimeField(auto_now=True)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_reports', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'kind', 'month', 'year')},
            },
        ),
    ]
