# Generated by Django 6.0.7 on 2026-08-31 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_gradingconfig_kpi_mode'),
        ('kpi', '0002_exportedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpisession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KpiHourTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('target_minutes_per_month', models.PositiveIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_hour_targets', to='accounts.tenant')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('tenant', 'position')},
            },
        ),
    ]
