# Generated by Django 6.0.7 on 2026-08-13 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('employees', '0014_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hoc', 'Chứng chỉ khóa học'), ('thi', 'Chứng chỉ bài thi'), ('chuong_trinh', 'Chứng chỉ chương trình')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('template_pdf_url', models.URLField(blank=True, max_length=500)),
                ('fields_config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CertProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('chuyen_mon', 'Đào tạo kỹ năng nghề'), ('bql', 'Ban quản lý')], max_length=20)),
                ('rule_config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_programs', to='integration.certificatetemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_programs', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('lesson', 'Bài học'), ('course', 'Toàn bộ khóa học')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('kem_tai_cho', 'Kèm tại chỗ'), ('video_nhom', 'Học nhóm qua video'), ('checklist_giay', 'Checklist giấy'), ('khac', 'Khác')], default='kem_tai_cho', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_confirmations_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_confirmations', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_confirmations', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='XapiStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('viewed', 'Đã xem'), ('started', 'Đã bắt đầu'), ('completed', 'Đã hoàn thành'), ('passed', 'Đạt'), ('failed', 'Không đạt'), ('confirmed_offline', 'Xác nhận offline')], max_length=20)),
                ('object_type', models.CharField(choices=[('lesson', 'Bài học'), ('course', 'Khóa học'), ('assessment', 'Đề thi')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('context_json', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xapi_statements', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xapi_statements', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CertificateIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('course', 'Khóa học'), ('assessment', 'Đề thi'), ('program', 'Chương trình')], max_length=20)),
                ('ref_id', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates_issued', to='accounts.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued', to='integration.certificatetemplate')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to='integration.certprogram')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('employee', 'ref_type', 'ref_id')},
            },
        ),
    ]
