# Generated by Django 6.0.7 on 2026-08-15 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_groups', to='accounts.tenant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='accounts.tenant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='dashboard.competencygroup')),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['order'],
                'unique_together': {('tenant', 'group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DashboardIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('group_label', models.CharField(blank=True, max_length=100)),
                ('role_scope', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('direction', models.CharField(choices=[('higher_better', 'Cao tốt'), ('lower_better', 'Thấp tốt'), ('none', 'Không tô màu (danh sách/biểu đồ)')], default='none', max_length=20)),
                ('green_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('yellow_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_indicators', to='accounts.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PositionGroupWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_weights', to='dashboard.competencygroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_group_weights', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'position', 'group')},
            },
        ),
        migrations.CreateModel(
            name='PositionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('target_score', models.IntegerField()),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_targets', to='dashboard.competency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_targets', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'position', 'competency')},
            },
        ),
    ]
