# Generated by Django 6.0.7 on 2026-08-15 08:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_weight', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5)),
                ('practice_weight', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scoring_config', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ClsExamCompetencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cls_exam_maps', to='dashboard.competency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cls_exam_competency_maps', to='accounts.tenant')),
            ],
            options={
                'ordering': ['exam_name'],
                'unique_together': {('tenant', 'exam_name')},
            },
        ),
    ]
