# Generated by Django 6.0.7 on 2026-08-17 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('dashboard', '0002_competencyscoringconfig_clsexamcompetencymap'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCostSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_url', models.URLField(blank=True, max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_cost_source', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cost_type', models.CharField(choices=[('trainer_salary', 'Lương & phụ cấp trainer'), ('materials', 'Tài liệu & in ấn'), ('software', 'Phần mềm / LMS'), ('facilities', 'Cơ sở vật chất'), ('travel', 'Ăn ở & đi lại'), ('other', 'Khác')], max_length=20)),
                ('scope', models.CharField(choices=[('system', 'Toàn hệ thống'), ('region', 'Vùng'), ('restaurant', 'Nhà hàng')], default='system', max_length=20)),
                ('unit_code', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_costs', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'month', 'year', 'cost_type', 'scope', 'unit_code')},
            },
        ),
    ]
