# Generated by Django 6.0.7 on 2026-08-17 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('dashboard', '0003_trainingcostsource_trainingcost'),
        ('employees', '0014_employee_user'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competency_snapshot', to='employees.employee')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_snapshots', to='restaurants.restaurant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_snapshots', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('gap', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='dashboard.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_score_snapshots', to='employees.employee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='dashboard.competencygroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_score_snapshots', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('employee', 'competency')},
            },
        ),
    ]
