# Generated by Django 6.0.7 on 2026-08-15 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('exams', '0002_assessment_sync_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='dashboard.competency'),
        ),
    ]
