# Generated by Django 6.0.7 on 2026-08-19 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('exams', '0003_assessment_competency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='proctoring_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions_per_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='review_mode',
            field=models.CharField(choices=[('none', 'Không'), ('score_only', 'Không chi tiết điểm'), ('full_detail', 'Chi tiết điểm từng câu')], default='full_detail', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='show_countdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='show_grade_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='show_score',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('target_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('closed', 'Đã đóng')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='exams.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='exams.examsession'),
        ),
    ]
