# Generated by Django 6.0.7 on 2026-08-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_competencysnapshot_competencyscoresnapshot'),
        ('exams', '0004_assessment_proctoring_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='dashboard.competency'),
        ),
    ]
