# Generated by Django 6.0.7 on 2026-08-20 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('exams', '0005_question_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='access_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctoring_snapshot_interval_sec',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='assessment',
            name='require_fullscreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tab_leave_auto_submit_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='flagged_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('no_face', 'Không thấy khuôn mặt'), ('multi_face', 'Nhiều hơn 1 khuôn mặt'), ('tab_leave', 'Rời tab'), ('blur', 'Mất focus cửa sổ'), ('snapshot', 'Ảnh chụp định kỳ'), ('fullscreen_exit', 'Thoát toàn màn hình')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='exams.attempt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='accounts.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
