# Generated by Django 6.0.7 on 2026-08-27 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_assessment_access_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='proctors',
            field=models.ManyToManyField(blank=True, related_name='proctoring_exam_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsession',
            name='supervised_by_restaurant_camera',
            field=models.BooleanField(default=False),
        ),
    ]
