# Generated by Django 6.0.7 on 2026-08-12 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('employees', '0014_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('objective', models.TextField(blank=True)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('est_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20)),
                ('competency_tag', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='accounts.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Đã gán'), ('in_progress', 'Đang học'), ('completed', 'Hoàn thành')], default='assigned', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Gán tay'), ('auto', 'Tự động')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_assigned', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('course', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('video_r2', 'Video (R2)'), ('video_youtube', 'Video (YouTube)'), ('video_vimeo', 'Video (Vimeo)'), ('pdf', 'PDF'), ('text', 'Văn bản'), ('link', 'Liên kết')], max_length=20)),
                ('content_url', models.URLField(blank=True, max_length=500)),
                ('content_html', models.TextField(blank=True)),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('anti_seek', models.BooleanField(default=False)),
                ('complete_rule', models.CharField(choices=[('watch_pct', 'Xem đủ % video'), ('open', 'Mở bài là xong'), ('mark', 'Tự đánh dấu hoàn thành'), ('quiz', 'Làm bài kiểm tra')], default='mark', max_length=20)),
                ('pass_watch_pct', models.IntegerField(default=80)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='accounts.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chưa bắt đầu'), ('in_progress', 'Đang học'), ('done', 'Hoàn thành')], default='pending', max_length=20)),
                ('watched_pct', models.IntegerField(default=0)),
                ('last_position_sec', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.lesson')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
