# Generated by Django 6.0.7 on 2026-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sync_course_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
