# Generated by Django 6.0.7 on 2026-08-14 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('courses', '0002_course_sync_course_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('video_r2', 'Video (R2)'), ('video_youtube', 'Video (YouTube)'), ('video_vimeo', 'Video (Vimeo)'), ('pdf', 'PDF'), ('text', 'Văn bản'), ('link', 'Liên kết'), ('scorm', 'SCORM (Articulate 360...)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScormPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('scorm_12', 'SCORM 1.2'), ('scorm_2004', 'SCORM 2004')], max_length=20)),
                ('storage_prefix', models.CharField(max_length=500)),
                ('launch_path', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_package', to='courses.lesson')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_packages', to='accounts.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorm_packages_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScormTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmi_json', models.JSONField(blank=True, default=dict)),
                ('lesson_status', models.CharField(blank=True, max_length=20)),
                ('score_raw', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_tracking', to='courses.lessonprogress')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_trackings', to='accounts.tenant')),
            ],
        ),
    ]
