# Generated by Django 6.0.7 on 2026-08-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('courses', '0004_course_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='face_pause_stop_sec',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='face_pause_warn_sec',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='max_watched_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('paused_face_lost', 'Tự tạm dừng (mất khuôn mặt)'), ('resumed', 'Tiếp tục phát')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='courses.lessonprogress')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_watch_events', to='accounts.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
