# Generated by Django 6.0.7 on 2026-07-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cls_sync', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='courseresult',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='accounts.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('employee', 'exam_name', 'attempt')},
        ),
    ]
