# Generated by Django 6.0.7 on 2026-07-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cls_sync', '0002_initial'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseresult',
            unique_together={('employee', 'course_name')},
        ),
    ]
