# Generated by Django 6.0.7 on 2026-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls_sync', '0003_alter_courseresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='exam_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
