# Generated by Django 6.0.7 on 2026-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls_sync', '0005_examresult_score_adjusted_examscoreadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
