# Generated by Django 6.0.7 on 2026-07-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls_sync', '0006_examresult_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
