# Generated by Django 6.0.7 on 2026-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls_sync', '0007_courseresult_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='source',
            field=models.CharField(choices=[('cls', 'CLS (đồng bộ ngoài)'), ('internal_lms', 'Nội bộ (Khóa học/Kỳ thi mới)')], default='cls', max_length=20),
        ),
        migrations.AddField(
            model_name='examresult',
            name='source',
            field=models.CharField(choices=[('cls', 'CLS (đồng bộ ngoài)'), ('internal_lms', 'Nội bộ (Khóa học/Kỳ thi mới)')], default='cls', max_length=20),
        ),
    ]
