# Generated by Django 6.0.7 on 2026-07-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('operation_unit', models.CharField(blank=True, choices=[('production', 'Sản xuất'), ('office', 'Văn phòng'), ('restaurant', 'Nhà hàng')], max_length=20)),
                ('job_level', models.CharField(blank=True, max_length=100)),
                ('level_group', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('employee_status', models.CharField(choices=[('probation', 'Thử việc'), ('active', 'Chính thức'), ('resigned', 'Nghỉ việc')], default='probation', max_length=20)),
                ('probation_days', models.IntegerField(blank=True, null=True)),
                ('skill_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skill_result', models.CharField(blank=True, max_length=50)),
                ('shift_ops', models.CharField(blank=True, max_length=50)),
                ('office_result', models.CharField(blank=True, max_length=50)),
                ('final_result', models.CharField(blank=True, max_length=50)),
                ('commission_status', models.CharField(blank=True, max_length=50)),
                ('retrain_deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
