# Generated by Django 6.0.7 on 2026-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_levelupenrollment_proposal_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pass_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
