# Generated by Django 6.0.7 on 2026-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_pass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resigned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
