# Generated by Django 6.0.7 on 2026-08-26 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_passwordsettoken'),
        ('courses', '0005_lesson_face_pause_stop_sec_and_more'),
        ('employees', '0014_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # LUU Y: khong bao gom cac AlterField 'id' (hrsyncsource/levelupenrollment/mgmtdevelopment/
    # recruitmentsource/talentreview) ma makemigrations tu goi y them - do la DRIFT CO SAN tu
    # truoc (BigAutoField vs AutoField), khong lien quan gi models moi o day; theo dung le thuong
    # cua repo nay la bo qua, khong commit (xem cac dot truoc).
    operations = [
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_create_account', models.BooleanField(default=False)),
                ('auto_enroll_onboarding', models.BooleanField(default=False)),
                ('send_welcome_email', models.BooleanField(default=False)),
                ('welcome_email_subject', models.CharField(blank=True, default='Chào mừng {ten_nhan_su} gia nhập {ten_he_thong}', max_length=255)),
                ('welcome_email_body', models.TextField(blank=True, default='Xin chào {ten_nhan_su},\n\nBạn đã được tạo tài khoản đào tạo tại {ten_he_thong} (mã nhân sự {ma_nhan_su}, nhà hàng {nha_hang}, vị trí {vi_tri}).\n\nTên đăng nhập: {ten_dang_nhap}\nVui lòng đặt mật khẩu lần đầu tại: {link_dat_mat_khau}\n\nTrân trọng.')),
                ('sender_display_name', models.CharField(blank=True, default='Phòng Đào tạo', max_length=255)),
                ('cc_recipients', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to='accounts.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingCourseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_rules', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_course_rules', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'position', 'course')},
            },
        ),
    ]
