# Generated by Django 6.0.7 on 2026-08-27 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_passwordsettoken'),
        ('employees', '0015_automationsettings_onboardingcourserule'),
        ('exams', '0007_examsession_proctors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='auto_assign_probation_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='auto_send_probation_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='require_approval_before_exam',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='result_email_body',
            field=models.TextField(blank=True, default='Kính gửi nhà hàng {nha_hang},\n\nNhân sự {ten_nhan_su} (mã {ma_nhan_su}, vị trí {vi_tri}) có kết quả thử việc: {ket_qua}.\nNgày Pass: {ngay_pass}\nNgày lương chính thức: {ngay_luong_chinh_thuc}\n\nTrân trọng, {ten_he_thong}.'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='result_email_subject',
            field=models.CharField(blank=True, default='Kết quả thử việc: {ten_nhan_su} - {ket_qua}', max_length=255),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='salary_effective_rule',
            field=models.CharField(choices=[('pass_date', 'Ngày Pass thử việc'), ('next_month_first', 'Ngày 1 tháng kế tiếp')], default='pass_date', max_length=20),
        ),
        # LUU Y: khong bao gom cac AlterField 'id' (hrsyncsource/levelupenrollment/mgmtdevelopment/
        # recruitmentsource/talentreview) ma makemigrations tu goi y them - drift co san tu truoc
        # (BigAutoField vs AutoField), khong lien quan gi thay doi o day; theo le thuong cua repo
        # nay la bo qua, khong commit (xem cac dot truoc - 0015 cung da lam vay).
        migrations.CreateModel(
            name='ProbationExamCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_approval', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending_approval', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_exam_candidates', to='exams.assessment')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_exam_candidates', to='employees.employee')),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_exam_candidates', to='exams.examsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_exam_candidates', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='ProbationExamRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_exam_rules', to='exams.assessment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_exam_rules', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ProbationResultNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass thử việc'), ('failed', 'Không đạt')], max_length=10)),
                ('decision_date', models.DateField()),
                ('salary_effective_date', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_result_notifications', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_result_notifications', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('employee', 'result', 'decision_date')},
            },
        ),
    ]
