# Generated by Django 6.0.7 on 2026-08-27 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_passwordsettoken'),
        ('employees', '0016_probation_exam_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='remind_days_before_deadline',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='remind_managers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='remind_repeat_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='remind_untrained_after_days',
            field=models.PositiveIntegerField(default=3),
        ),
        # LUU Y: khong bao gom cac AlterField 'id' (hrsyncsource/levelupenrollment/mgmtdevelopment/
        # recruitmentsource/talentreview) ma makemigrations tu goi y them - drift co san tu truoc
        # (BigAutoField vs AutoField), khong lien quan gi thay doi o day; theo le thuong cua repo
        # nay la bo qua, khong commit (xem 0015/0016 cung da lam vay).
        migrations.CreateModel(
            name='ProbationReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('probation_untrained', 'Còn nội dung chưa đào tạo'), ('probation_deadline', 'Sắp đến hạn thử việc')], max_length=30)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reminder_logs', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reminder_logs', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('employee', 'category')},
            },
        ),
    ]
