# Generated by Django 6.0.7 on 2026-07-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('doc_url', models.URLField(blank=True)),
                ('level_group', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='accounts.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chưa bắt đầu'), ('in_progress', 'Đang thực hiện'), ('done', 'Hoàn thành')], default='pending', max_length=20)),
                ('img_tailieu', models.URLField(blank=True)),
                ('img_lythuyet', models.URLField(blank=True)),
                ('img_thuchanh', models.URLField(blank=True)),
                ('sign_trainer', models.URLField(blank=True)),
                ('sign_trainee', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='checklist.checklist')),
            ],
        ),
    ]
