# Generated by Django 6.0.7 on 2026-07-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogress',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='img_lythuyet',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='img_tailieu',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='img_thuchanh',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='sign_trainee',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='sign_trainer',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
