# Generated by Django 6.0.7 on 2026-07-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_trainingprogress_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('done', 'Hoàn thành'), ('update', 'Cần cập nhật'), ('digitize', 'Cần số hóa')], default='done', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, default='v1.0', max_length=20),
        ),
    ]
