# Generated by Django 6.0.7 on 2026-08-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_document_position_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
