# Generated by Django 6.0.7 on 2026-08-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_checklist_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='standard_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
