# Generated by Django 6.0.7 on 2026-09-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_document_standard_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='phase',
            field=models.CharField(choices=[('core', 'Cơ bản (thử việc)'), ('completion', 'Hoàn thiện')], default='core', max_length=20),
        ),
    ]
